import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

import { THEME_TOKENS } from "./tokens";
import { themeColorNames } from "./types";
import type { GeneratedArtifact, ThemeColors } from "./types";

const GENERATED_HEADER =
  "/* This file is generated by @hello/ui-tokens. Do not edit manually. */";

const indent = (value: string, spaces = 2) =>
  value
    .split("\n")
    .map((line) => `${" ".repeat(spaces)}${line}`)
    .join("\n");

const colorVariableLines = (colors: ThemeColors) =>
  themeColorNames.map((name) => `--${name}: ${colors[name]};`).join("\n");

const toHsl = (value: string) => `hsl(${value})`;

export const generateWebThemeCss = () => {
  const webColorThemeLines = themeColorNames
    .map((name) => `--color-${name}: hsl(var(--${name}));`)
    .join("\n");

  return `${GENERATED_HEADER}

@custom-variant dark (&:is(.dark *));

:root {
${indent(colorVariableLines(THEME_TOKENS.light.colors))}
  --radius: ${THEME_TOKENS.radii.base};
}

.dark {
${indent(colorVariableLines(THEME_TOKENS.dark.colors))}
}

@theme inline {
${indent(webColorThemeLines)}
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}`;
};

export const generateNativeThemeCss = () => `${GENERATED_HEADER}

@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
${indent(colorVariableLines(THEME_TOKENS.light.colors))}
  --radius: ${THEME_TOKENS.radii.base};
}

.dark:root {
${indent(colorVariableLines(THEME_TOKENS.dark.colors))}
}`;

export const generateNativeThemeTs = () => {
  const nativeThemeLines = (colors: ThemeColors) =>
    themeColorNames
      .map((name) => `    "${name}": "${toHsl(colors[name])}",`)
      .join("\n");

  return `${GENERATED_HEADER}

export const THEME = {
  light: {
${nativeThemeLines(THEME_TOKENS.light.colors)}
  },
  dark: {
${nativeThemeLines(THEME_TOKENS.dark.colors)}
  }
} as const;

export const NAV_THEME = {
  light: {
    background: "${toHsl(THEME_TOKENS.light.colors.background)}",
    border: "${toHsl(THEME_TOKENS.light.colors.border)}",
    card: "${toHsl(THEME_TOKENS.light.colors.card)}",
    notification: "${toHsl(THEME_TOKENS.light.colors.destructive)}",
    primary: "${toHsl(THEME_TOKENS.light.colors.primary)}",
    text: "${toHsl(THEME_TOKENS.light.colors.foreground)}"
  },
  dark: {
    background: "${toHsl(THEME_TOKENS.dark.colors.background)}",
    border: "${toHsl(THEME_TOKENS.dark.colors.border)}",
    card: "${toHsl(THEME_TOKENS.dark.colors.card)}",
    notification: "${toHsl(THEME_TOKENS.dark.colors.destructive)}",
    primary: "${toHsl(THEME_TOKENS.dark.colors.primary)}",
    text: "${toHsl(THEME_TOKENS.dark.colors.foreground)}"
  }
} as const;
`;
};

export const generateDesktopThemeTs = () => `${GENERATED_HEADER}

export const desktopWindowBackground = "${THEME_TOKENS.desktop.windowBackground}";
`;

export const getGeneratedArtifacts = (
  repoRoot: string
): GeneratedArtifact[] => [
  {
    path: path.join(repoRoot, "apps/web/src/app/theme.css"),
    content: generateWebThemeCss()
  },
  {
    path: path.join(repoRoot, "apps/mobile/global.css"),
    content: generateNativeThemeCss()
  },
  {
    path: path.join(repoRoot, "apps/mobile/src/lib/theme.ts"),
    content: generateNativeThemeTs()
  },
  {
    path: path.join(repoRoot, "apps/desktop/src/generated/theme.ts"),
    content: generateDesktopThemeTs()
  }
];

const normalizeTrailingNewline = (content: string) => `${content.trimEnd()}\n`;

export const writeGeneratedArtifacts = async (repoRoot: string) => {
  const artifacts = getGeneratedArtifacts(repoRoot);

  await Promise.all(
    artifacts.map(async (artifact) => {
      await mkdir(path.dirname(artifact.path), { recursive: true });
      await writeFile(
        artifact.path,
        normalizeTrailingNewline(artifact.content),
        "utf8"
      );
    })
  );
};

export const checkGeneratedArtifacts = async (repoRoot: string) => {
  const artifacts = getGeneratedArtifacts(repoRoot);

  for (const artifact of artifacts) {
    let currentContent: string;

    try {
      currentContent = await readFile(artifact.path, "utf8");
    } catch {
      throw new Error(`Generated artifact is missing: ${artifact.path}`);
    }

    if (
      normalizeTrailingNewline(currentContent) !==
      normalizeTrailingNewline(artifact.content)
    ) {
      throw new Error(`Generated artifact is out of date: ${artifact.path}`);
    }
  }
};

export const resolveRepoRoot = () => path.resolve(process.cwd(), "../..");
